<?php include_once("includes/basic_includes.php");?>
<?php include_once("functions.php"); ?>

<!DOCTYPE HTML>
<html>
<head>
<title>Find Your Perfect Partner - Matrimony | Faq :: Matrimony
</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="css/bootstrap-3.1.1.min.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<!-- Custom Theme files -->
<link href="css/style.css" rel='stylesheet' type='text/css' />
<link href='//fonts.googleapis.com/css?family=Oswald:300,400,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>
<!----font-Awesome----->
<link href="css/font-awesome.css" rel="stylesheet"> 
<!----font-Awesome----->
<script>
$(document).ready(function(){
    $(".dropdown").hover(            
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');        
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');       
        }
    );
});
</script>
</head>
<body>
<!-- ============================  Navigation Start =========================== -->
<?php include_once("includes/navigation.php");?>
<!-- ============================  Navigation End ============================ -->
<div class="grid_3">
  <div class="container">
   <div class="breadcrumb1">
     <ul>
        <a href="index.php"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">FAQ</li>
     </ul>
   </div>
   <dl class="faq-list">
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4> Are all people allowed to become members?</h4>
	</dt>
	<dd>
	<h4 class="marker1">A.</h4>
	<p class="m_4">Modern Day Matrimony  does not discriminate regarding caste, color, religion or in any way. We believe all people are the same and deserve the chance to enjoy the success of an arranged marriage through Modern Day Matrimony.
	</p>
	</dd>	<dt class="faq-list_h">

	<h4 class="marker">Q?</h4>
	<h4>What is the cost of membership?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4">There is no charge for being a membership of Modern Day Matrimony.
	</p>
	</dd>
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4> Can I meet my life partner online?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4">.Yes, you can find your life partner online. Thousands of people have so why not you? Online matchmaking is changing the way people look for marriage partners. Be part of the change.
	</p>
	</dd>
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4>How to become successful on Modern Day Matrimony in 4 simple steps?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4">Your Personal Profile

	<p class="m_4"> Give as much information as you can about yourself and the expectations you have about the person you are searching as your potential life partner. Well written profiles have higher chances of success. Try to keep your profile current.

Your photo

<p class="m_4"> Your profile is incomplete if does not have a photo. A good picture is worth thousand words. We are baffled why some of the members are shy about uploading photo. Here you are about to make the most important decision of your life yet, many still do not post photos. You do it on Facebook why the hesitation on online matchmaking. It also important to upload a picture which clear, current and the one you like most. In other words post a picture which is the most flattering.

Become a premium member

<p class="m_4"> If you are really serious and want to communicate effectively become a premium member. Free member can only express interest and reply to messages sent by premium member.

Have a responsible attitude

<p class="m_4"> Check your mail for messages and reply back as soon as possible. Login to the site for new members, you never know one of them may become your life partner. Remember being persistent and having responsible attitude has never hurt anyone. Modern Day Marriage is like a river. New members register every day. Checking back often improves the chance of finding the ideal partner.
</p>
</dd>
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4>Where are my email messages being sent?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4">All email messages generated by the site are sent to the registered email address of the member as well as to the inbox section of Modern Day Matrimony.
	</p>
	</dd>
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4>How do I pay for my membership?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4">Payments to Premium memberships can be made by Visa, Master Card, Discover, American Express, Paypal and most ATM cards with the Visa or Mastercard logo.
        </p>
</dd>
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4> How secure is my credit card information on Modern Day Matrimony?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4">1. Your credit card details are not recorded by our site.
                   <p class="m_4"> 	2. When you enter your credit card details you will notice a lock sign at the bottom of the page. This is the same security used by banks.
 </p>
	</dd>
   </dl>
  </div>
</div>


<?php include_once("footer.php");?>

